"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, CircleAlert, Download, Sparkles } from "lucide-react";
import { demoQuotes, demoRfx, lineItems, vendors } from "@/lib/fixtures";
import { RfxChat } from "@/components/rfx-chat";
import { jsPDF } from "jspdf";
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
export default function DemoRfxPage() {
  const [tab, setTab] = useState<"Comparison" | "Overview" | "Recommendation">("Comparison");
  const [chosen, setChosen] = useState<Record<string, string>>(() => Object.fromEntries(lineItems.map((item, i) => [item.id, i % 3 === 0 ? "apex" : "globalpak"])));
  const total = useMemo(() => lineItems.reduce((sum, item) => { const quote = demoQuotes.find((entry) => entry.lineItemId === item.id && entry.vendorId === chosen[item.id]); return sum + (quote?.normalizedUnitPrice || 0) * item.annualQuantity; }, 18500), [chosen]);
  const context = `RFx ${demoRfx.title}. Eligible: Apex, Bharat, SwiftBox, GlobalPak. Ineligible: ValueCorr (capacity). Confirmed values: ${demoQuotes.filter((q) => q.confidence === "confirmed").length}; excluded review values: ${demoQuotes.filter((q) => q.confidence === "needs_review").length}. Proposed allocation total: ${money.format(total)} including ₹18,500 GlobalPak freight once.`;
  const exportCsv = () => { const rows = ["SKU,Item,Annual quantity,Selected vendor,Normalized INR per piece", ...lineItems.map((item) => { const quote = demoQuotes.find((q) => q.lineItemId === item.id && q.vendorId === chosen[item.id]); return `${item.sku},${item.name},${item.annualQuantity},${vendors.find((v) => v.id === chosen[item.id])?.name},${quote?.normalizedUnitPrice ?? ""}`; })]; const url = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "rfx-comparison.csv"; link.click(); URL.revokeObjectURL(url); };
  const exportPdf = () => { const pdf = new jsPDF(); pdf.setFontSize(19); pdf.text("RFX Pilot — Award decision summary", 16, 20); pdf.setFontSize(11); pdf.text(demoRfx.title, 16, 30); pdf.text(`Recommended split award: Apex Cartons + GlobalPak Imports`, 16, 42); pdf.text(`Estimated GST-inclusive landed cost: ${money.format(total)}`, 16, 50); pdf.text("Eligibility: 4 of 5 vendors eligible. ValueCorr excluded for capacity.", 16, 62); pdf.text("Risk note: ₹18,500 GlobalPak freight counted once; low-confidence values excluded.", 16, 70); pdf.text("Allocation", 16, 84); lineItems.slice(0, 18).forEach((item, index) => pdf.text(`${item.sku}: ${vendors.find((v) => v.id === chosen[item.id])?.name}`, 16, 92 + index * 7)); pdf.save("rfx-award-decision-summary.pdf"); };
  return <main className="event-shell"><header className="event-top"><a href="/" className="back"><ArrowLeft size={17} /> Workspace</a><span className="event-status">Analysis ready</span></header><section className="event-heading"><div><p className="panel-label">{demoRfx.plant.toUpperCase()}</p><h1>{demoRfx.title}</h1><p className="subcopy">Closed RFx · 30 line items · confirmed-data comparison</p></div><div className="event-actions"><button className="export-button" onClick={exportCsv}><Download size={16} /> CSV</button><button className="export-button" onClick={exportPdf}><Download size={16} /> PDF</button><RfxChat context={context} /></div></section><nav className="tabs">{(["Comparison", "Overview", "Recommendation"] as const).map((name) => <button className={tab === name ? "active" : ""} onClick={() => setTab(name)} key={name}>{name}</button>)}</nav>
  {tab === "Overview" && <section className="overview-grid"><div><b>4 / 5</b><span>eligible vendors</span></div><div><b>27 / 30</b><span>Bharat lines quoted</span></div><div><b>5</b><span>values need review</span></div><div><b>1</b><span>ineligible quote retained</span></div></section>}
  {tab === "Recommendation" && <section className="recommendation"><p className="panel-label">PROPOSED SPLIT AWARD</p><h2>Apex Cartons + GlobalPak Imports</h2><p>GlobalPak holds 20 lowest confirmed lines; Apex holds 10 lines where quality and delivery offset the price premium.</p><strong>{money.format(total)} <small>GST-inclusive estimated landed cost</small></strong><p className="risk-note">Includes ₹18,500 GlobalPak vendor-level freight once. Excludes low-confidence and ineligible values.</p><button onClick={() => setTab("Comparison")}>Edit allocation in comparison</button></section>}
  {tab === "Comparison" && <><section className="vendor-strip">{vendors.map((vendor) => <article className={`vendor-card ${vendor.eligibility === "ineligible" ? "ineligible" : ""}`} key={vendor.id}><div className="vendor-card-top">{vendor.eligibility === "eligible" ? <BadgeCheck size={17} /> : <CircleAlert size={17} />}<span>{vendor.eligibility}</span></div><h3>{vendor.name}</h3><p>{vendor.coverage}/30 · {vendor.currency}</p>{vendor.eligibilityReason && <small>{vendor.eligibilityReason}</small>}</article>)}</section><div className="comparison-note"><Sparkles size={16} /> Confirmed normalized prices only. Review and ineligible data is visible but excluded from selection.</div><div className="comparison-wrap"><table><thead><tr><th>Line item</th><th>Annual qty</th>{vendors.map((vendor) => <th className={vendor.eligibility === "ineligible" ? "muted-column" : ""} key={vendor.id}>{vendor.name}</th>)}</tr></thead><tbody>{lineItems.map((item) => <tr key={item.id}><td><b>{item.sku}</b><span>{item.name}</span></td><td>{item.annualQuantity.toLocaleString()}</td>{vendors.map((vendor) => { const quote = demoQuotes.find((entry) => entry.lineItemId === item.id && entry.vendorId === vendor.id)!; const selected = chosen[item.id] === vendor.id; const disabled = vendor.eligibility === "ineligible" || !quote.normalizedUnitPrice || quote.confidence !== "confirmed"; return <td className={vendor.eligibility === "ineligible" ? "muted-column" : ""} key={vendor.id}><button disabled={disabled} onClick={() => setChosen((current) => ({ ...current, [item.id]: vendor.id }))} className={selected ? "quote selected" : "quote"}><b>{quote.normalizedUnitPrice ? `₹${quote.normalizedUnitPrice.toFixed(2)}` : "—"}</b><span>{quote.sourceUnit}</span>{quote.confidence === "needs_review" && <em>Needs review</em>}</button></td>; })}</tr>)}</tbody></table></div></>}</main>;
}
